name: Aggregate Mocks to mocks.json

on:
  push:
    branches:
      - main
    paths:
      - 'mocks/**/*.json'
      - 'functions.js'
  pull_request:
    types: [closed]
    branches:
      - main

# Add write permissions for the workflow
permissions:
  contents: write

jobs:
  aggregate-mocks:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci || npm install
      
      - name: Validate mock JSON files
        run: npm run validate:mocks
      
      - name: Aggregate mock JSON files
        run: npm run aggregate
      
      - name: Check if mocks.json or functions.js changed
        id: check_changes
        run: |
          git add mocks.json functions.js 2>/dev/null || true
          if git diff --staged --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "mocks_changed=false" >> $GITHUB_OUTPUT
            echo "functions_changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            
            # Check specifically what changed
            if git diff --staged --name-only | grep -q "mocks.json"; then
              echo "mocks_changed=true" >> $GITHUB_OUTPUT
            else
              echo "mocks_changed=false" >> $GITHUB_OUTPUT
            fi
            
            if git diff --staged --name-only | grep -q "functions.js"; then
              echo "functions_changed=true" >> $GITHUB_OUTPUT
            else
              echo "functions_changed=false" >> $GITHUB_OUTPUT
            fi
          fi
      
      - name: Commit and push changes
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Build commit message based on what changed
          COMMIT_MSG="chore: Auto-update "
          if [ "${{ steps.check_changes.outputs.mocks_changed }}" == "true" ]; then
            COMMIT_MSG="${COMMIT_MSG}mocks.json "
          fi
          if [ "${{ steps.check_changes.outputs.functions_changed }}" == "true" ]; then
            COMMIT_MSG="${COMMIT_MSG}functions.js "
          fi
          
          git commit -m "${COMMIT_MSG}"
          git push
      
      - name: Wait for CDN cache refresh
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          echo "Waiting 30 seconds for AEM/CDN to refresh cache..."
          echo "   This ensures the updated mocks.json is available when webhook is triggered"
          sleep 30
          echo "CDN refresh wait completed"
      
      - name: Trigger stub-generator reload
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          echo "Notifying stub-generator of updates..."
          
          # Build list of modified files
          MODIFIED_FILES="["
          if [ "${{ steps.check_changes.outputs.mocks_changed }}" == "true" ]; then
            MODIFIED_FILES="${MODIFIED_FILES}\"mocks.json\""
          fi
          if [ "${{ steps.check_changes.outputs.functions_changed }}" == "true" ]; then
            if [ "${{ steps.check_changes.outputs.mocks_changed }}" == "true" ]; then
              MODIFIED_FILES="${MODIFIED_FILES}, "
            fi
            MODIFIED_FILES="${MODIFIED_FILES}\"functions.js\""
          fi
          MODIFIED_FILES="${MODIFIED_FILES}]"
          
          echo "Modified files: ${MODIFIED_FILES}"
          
          # Replace with your actual stub-generator URL
          STUB_GENERATOR_URL="${{ secrets.STUB_GENERATOR_URL || 'http://localhost:10000' }}"
          
          # Add timestamp for cache busting
          TIMESTAMP=$(date +%s)
          
          curl -X POST "${STUB_GENERATOR_URL}/api/webhook/github-mocks-updated" \
            -H "Content-Type: application/json" \
            -d "{
              \"repository\": \"${{ github.repository }}\",
              \"commits\": [{\"modified\": ${MODIFIED_FILES}}],
              \"pusher\": {\"name\": \"github-actions[bot]\"},
              \"timestamp\": ${TIMESTAMP}
            }" \
            --fail-with-body \
            --max-time 30 \
            || echo "Warning: Failed to notify stub-generator (server may be offline)"
          
          echo "Notification sent to stub-generator"

